-- Base from http://stackoverflow.com/questions/264914/how-do-i-calculate-tables-size-in-oracle/266964#266964
SELECT
   owner, 
   table_name,
   TRUNC(sum(bytes)/1024/1024) Meg,
   ROUND( ratio_to_report( sum(bytes) ) over () * 100) Percent
   ,to_number( -- SLOW
	 extractvalue(
       xmltype(
         dbms_xmlgen.getxml('select count(*) c from ' || owner || '.' || table_name)
       )
       ,'/ROWSET/ROW/C'
     )
   ) as rows_Count -- http://www.dba-oracle.com/t_count_rows_all_tables_in_schema.htm
FROM
(SELECT segment_name table_name, owner, bytes
 FROM dba_segments
 WHERE segment_type IN ('TABLE', 'TABLE PARTITION', 'TABLE SUBPARTITION')
 UNION ALL
 SELECT i.table_name, i.owner, s.bytes
 FROM dba_indexes i, dba_segments s
 WHERE s.segment_name = i.index_name
 AND   s.owner = i.owner
 AND   s.segment_type IN ('INDEX', 'INDEX PARTITION', 'INDEX SUBPARTITION')
 UNION ALL
 SELECT l.table_name, l.owner, s.bytes
 FROM dba_lobs l, dba_segments s
 WHERE s.segment_name = l.segment_name
 AND   s.owner = l.owner
 AND   s.segment_type IN ('LOBSEGMENT', 'LOB PARTITION')
 UNION ALL
 SELECT l.table_name, l.owner, s.bytes
 FROM dba_lobs l, dba_segments s
 WHERE s.segment_name = l.index_name
 AND   s.owner = l.owner
 AND   s.segment_type = 'LOBINDEX')
//WHERE owner in UPPER('&owner')
GROUP BY table_name, owner
//GROUP BY CUBE(table_name, owner)
HAVING SUM(bytes)/1024/1024 > 10  /* Ignore really small tables */
ORDER BY SUM(bytes) desc
;

SELECT *
FROM dba_tables
/


-- Base from http://stackoverflow.com/questions/264914/how-do-i-calculate-tables-size-in-oracle/266964#266964
WITH tables_size AS (
	SELECT
		segment_name table_name, owner, bytes
	FROM
		dba_segments
	WHERE
		segment_type IN ('TABLE', 'TABLE PARTITION', 'TABLE SUBPARTITION')

	UNION ALL

	SELECT
		i.table_name, i.owner, s.bytes
	FROM
		dba_indexes i, dba_segments s
	WHERE
		s.segment_name = i.index_name
		AND s.owner = i.owner
		AND s.segment_type IN ('INDEX', 'INDEX PARTITION', 'INDEX SUBPARTITION')

	UNION ALL

	SELECT
		l.table_name, l.owner, s.bytes
	FROM
		dba_lobs l
		JOIN dba_segments s ON(s.segment_type IN ('LOBSEGMENT', 'LOB PARTITION') AND s.segment_name = l.segment_name AND s.owner = l.owner)	

	UNION ALL

	SELECT
		l.table_name, l.owner, s.bytes
	FROM
		dba_lobs l
		JOIN dba_segments s ON (s.segment_type = 'LOBINDEX' AND s.owner = l.owner AND s.segment_name = l.index_name)
)
SELECT
	ts.owner,
	ts.table_name,
	TRUNC(sum(ts.bytes)/1024/1024) MB,
	ROUND( ratio_to_report( sum(bytes) ) over () * 100) as "%%"
	,t.NUM_ROWS
   ,to_number( -- SLOW
	 extractvalue(
       xmltype(
         dbms_xmlgen.getxml('select count(*) c from ' || ts.owner || '.' || ts.table_name)
       )
       ,'/ROWSET/ROW/C'
     )
   ) as real_rows_count -- http://www.dba-oracle.com/t_count_rows_all_tables_in_schema.htm
	,t.AVG_ROW_LEN
	,TRUNC(num_rows * avg_row_len / 1024 / 1024) as expected_size_Mb
	,t.LAST_ANALYZED
	,t.PARTITIONED
FROM
	tables_size ts
	JOIN dba_tables t ON (t.owner = ts.owner AND t.table_name = ts.table_name) -- https://docs.oracle.com/cd/B19306_01/server.102/b14237/statviews_2105.htm#REFRN20286
GROUP BY
	ts.table_name, ts.owner
	,t.NUM_ROWS
	,t.AVG_ROW_LEN
	,t.LAST_ANALYZED
	,t.PARTITIONED
//GROUP BY CUBE(table_name, owner)
HAVING SUM(bytes)/1024/1024 > 10  /* Ignore really small tables */
ORDER BY SUM(bytes) desc
;


SELECT
	TABLE_NAME, NUM_ROWS, AVG_ROW_LEN, NUM_ROWS * AVG_ROW_LEN / 1024 / 1024 as AVG_SIZE_MB
	,'|'
	,all_tables.*
FROM all_tables
WHERE tablespace_name NOT IN ('SYSTEM', 'SYSAUX')
	AND NUM_ROWS * AVG_ROW_LEN / 1024 / 1024 < 50 -- Less then 50Mb
	AND TABLE_NAME NOT LIKE '%#%'
ORDER BY AVG_SIZE_MB DESC NULLS LAST
/

SELECT *
FROM SYS.dba_extents
/

SELECT *
FROM ELA_DOCUMENT
WHERE ROWNUM <= 20

('LOG$FIN_PAYMENTS','ELA_AP_MOVEDOCUMENTS','LOG$DF_PRC_TRANSITIONS','DF_FLD_CRT','LOG$QU_DOC','QU_SWITCH','LOG$QU_SWITCH','ARCH_RE_HISTORY','RE_HISTORY','GKN_RE_REQUEST','NAL_EXP_RT_DEL','AR_ARRESTS','LOG_CONNECTIONS','LOG$VOL_EMPS','QU_PAY','LOG$ARCH_DOC_REL','ARCH_RE_VALUES','LOG$APP_RT','LOG$ISS_ISSUE','IG_REQUEST_MD_OBJECT_LNK','LOG$APP_PAY','LOG$ISS_ENT','BRG_ENT','BRG_ENT','RT_RS','CSE_ORDERS','LOG$APP_CHG','ARCH_RT_RS','ISS_PAY','LOG$ISS_DOC','LOG$QU_REF_OBJ','QU_95704000','LOG$ADR_ADDRESS_VOC' ,'LOG$CSE_HISTORY','LOG$ENT_ADDRESS','GKN_ANSWER_DOC','GKN_QUERY_DATA','IG_REMOTE_REQUEST_FOLDER_LNK','LOG$RT_ENT','ITO_SPISOK2','RE_VALUES','DF_FLD_CSE','ITO_GKN_LOG2','LOG$CRT_JOURNAL','LOG$ARCH_RT_ENT','LOG$DF_FLD_APP','ISS_CRT','APP_SWITCH','APP_ADD','LOG$ISS_PAY','ODS_OBJECTS','LOG$DF_FLD_ISS','ARCH_ENT_ENTITIES','ARCH_ENT_ENTITIES','LOG$GKN_ANSWER_DOC','NAL_EXPORTS','REP_DOC','QU_94146000','ITO_GKN_OUT','LOG$ENT_REPRESENTATIVES','ADR_ADDRESS_VOC_FULL','QU_93542000','EMPS_WORK_STAT','EXP_FL_OBJECTS' ,'RT_DOMAINS','LOG$ISS_CRT','AR_JOURNAL','LOG$CSE_CASES','LOG$DF_FLD_CRT','LOG$RE_PURPOSES','LOG$CSE_FOLDERS','QU_ENT_CANDIDATS','ITO_OKS_ZU','ELA_DELETED_DOCUMENT','LOG$RE_HISTORY','LOG$APP_SWITCH','AR_ENTITIES','AR_DOC','LOG$ARCH_RT_RS','AR_OBJECTS','QU_ENT_CANDIDATS','LOG$QU_ENT_CANDIDATS','TEST_ADR','ARCH_RT_ODS','RE_PARENTS','LOG$BRG_BARGAINS','LOG$QU_PAY','NAL_EXPORTS_DET_TMP','LOG$ARCH_RE_PURPOSES','RT_ODS','QU_95743000','QU_95749000','QU_95698000','QU_95687000','QU_95670000','AR_ENT_CANDIDATS' ,'ADR_KLADR','LOG$RT_RS','APP_AR','LOG$ARCH_RE_HISTORY','LOG$ARCH_RT_ODS','LOG$ODS_OBJECTS','AR_ADR_PRE','QU_92500000','LOG$AR_ARRESTS','QU_95746000','ARCH_ENT_ADDRESS','LOG$BRG_ENT','LOG$APP_ADD','ARCH_RT_DOMAINS','LOG$CSE_ORDERS','EXP_JOURNAL','AR_ENT_CANDIDATS','LOG$DF_FLD_CSE','LOG$REP_DOC','LOG$RT_ODS','APP_ODS','LOG$ARCH_RE_VALUES','LOG$AR_ENT_CANDIDATS','VOL_VOLUMES','ARCH_BRG_BARGAINS','ARCH_RE_O_ADR','QU_95752000','QU_95676000','NAL_JOBS','QU_95287000','APP_104999000','HEP_ERRORS','TRANS_FUSION_ENT' ,'NAL_CORRECT_RT','QU_94964000','QU_94924000','QU_94911000','RP_EMPS','ITO_SPISOK','ZKP_CHANGES','EXP_IMPORTS','TRANS_FUSION_ENT2','RP_EMP_TASKS','GKN_QUERY_DATA_BIN','ZKP_RE_OBJECTS','ARCH_RE_PARENTS','NAL_PERSMO_DOC','VOL_MISSING_REC','ARCH_DOC_FOUNDATIONS','GKN_QUERY','LOG$APP_ODS','LOG_CLIENTS','LOG$RE_VALUES','UC_ITEM','APP_104834000','TOAD_PLAN_TABLE','LOG$APP_AR','LOG$AR_OBJECTS','APP_105020000','ZKP_CHANGES_RE','LOG$AR_DOC','APP_104997000','ARCH_BRG_ENT','ARCH_BRG_ENT','CALENDAR_VOC','NAL_GOSNALINS_VOC' ,'TRANS_RTENT','NAL_IMPORTS','EXP_FIR_JOURNAL','STAGEPROF','LOG$ARCH_DOC_FOUNDATIONS','LOG$AR_JOURNAL','LOG$AR_ENTITIES','NEW_O_ADR','ODS_GROUPS','NAL_FRMT_FIELDS','CG_TEMPL_MEANINGS','LOG$RP_EMPS','UC_ITEM_LINK','MD_PROPS','APP_104737000','NAL_PERSMO_DOC','STAT_MERT_ODS_DOC','APP_105028000','QU_94408000','QU_93598000','QU_93595000','TMP_LOST_EXP_LOG_DEPTS','CG_PAR_EMP_VALUES','KLADR_ALTNAMES','NAL_PERSMO_ENT','APP_104653000','NAL_PERSMO_ENT','NAL_PERSMO_ACTENT_RT','QU_93545000','APP_104995000','APP_105001000' ,'NAL_FRMT_QUERY','APP_104654000','FIN_BANK_VOC','CG_REF_CODES','LOG$ODS_GROUPS','REAL_DEPENDENCIES','EXP_FL_JOURNAL','QU_94411000','QU_93548000','TMP_ODS_SQ_2016_3','TMP_ODS_SQ_2016_2','CURRENT_REG_NO','CMP_DETAILS','QU_92503000','LOG$VOL_SIGNS','LOG$RE_CONDS','RE_PURPOSE_VOC','ODS_LOCATIONS','QU_95365000','QU_95359000','LOG$CMP_DETAILS','CG_PARAMETERS','ODS_BUILDERS','CG_PAR_VALUES','APP_REQUIRED_DOC','CG_PARAMETERS_COPY','ARCH_RE_COMPLEX','RE_COMPLEX','HEP_ERRORS_TYPE_VOC','ENT_SYSTEMORG_VOC','ZKP_REF_CAT_UTIL_PURP' ,'LOG$FRM_LIST','NAL_ROSNEDV_VOC','NAL_PERSMO_ACTENT_RT','APP_REQ_DOC_DESC','AR_LOG','LOG$RE_COMPLEX','CSE_FRM','VOL_SIGNS','CG_MODULES','QU_96977000','CMP_OBJECTS','ADR_COUNTRIES_VOC','RE_CONDS','CG_PAR_USING','LOG$CMP_OBJECTS','LOG$ODS_LOCATIONS','MD_TABLES','NAL_FRMT_VIEWS','LOG$ODS_BUILDERS','QU_94405000','RP_ROLES','UC_SOURCE_VOC','ODS_BUILDERS','HEP_PROTOCOLS','APP_SUBJECT_VOC','ZKP_REF_D_UTIL','ELA_AUDIT','LOG$QU_RE_CND_DOCUMENTS','LOG$ARCH_BRG_ENT','DOC_NOTAR_VOC','CG_REPORTS','QU_RE_CND_DOCUMENTS' ,'UC_ITEM_ADD','NAL_FAUGI_VOC','RP_REGIONS','ADR_TYPES_SYNONYMS','MD_VOCS','NAL_EXPORTS_TMP','ADR_TYPES_VOC','LOG$FIN_BANK_VOC','LOG$ARCH_RE_COMPLEX','QU_92497000','LOG$VOL_QUE_VOLS','CG_TEMPLATES','ARCH_RT_CMP','RT_CMP','CG_HELP_ITEMS','NAL_EXP_TYPES','NAL_DISTRICTS','ZKP_REF_D_UTIL_NEW','VOL_QUEUES','MD_DEPENDENCIES','KLADR_SOCR','CG_FORM_ITEMS','VOL_QUE_VOLS','RT_RIGHTS_VOC','ENT_KOPF_VOC','NAL_FRMT_JOINS','RP_LOCAL_DEPTS','UC_CATEGORY_VOC','MD_OBJECTS','CRT_ADD','ODS_105000000','BRG_BARGAINS_VOC' ,'BRG_RT_INVOLVE_VOC','NAL_SETTINGS','RP_DEPTS','BACKUP_CSE_DOC','IG_PARAMETERS','CSE_STORAGE_VOC','DF_STG_TRANSITIONS','APP_SUBJECT_VOC_REL','APP_REGPERIOD_VOC','QU_REFERENCE_VOC','CALENDAR_SHIFT_VOC','DF_STAGES','LOG$VOL_QUEUES','QU_96955000','QUF_EMP_STG','ADR_KLADR_TYPES','RP_GROUPS','TMP_SEQ','LOG$ARCH_BRG_BARGAINS','DS_ACTION_LOG','CSE_CASES','NAL_JOB_STATUS_VOC','ZKP_REALTY_VOC','LOG$ARCH_RT_CMP','IG_MODULE','ELA_EVENT_TYPE','NAL_IMP_TYPES','IG_DEPTS','NAL_EXP_JOURNALS','NAL_IMP_FIELDS','BRG_RS_RESULT_VOC' ,'IG_ROUTE','CHECK_LOOP_ADR','QU_REGPERIOD_VOC','RAJONS','ZKP_REF_D_CATEGORIES_NEW','IG_REQUEST_STATUS_TYPE','REGPERIOD_SHIFT_VOC','ODS_104998000','DYN_GROUPS','LOG_REP_VOC','RT_DOMAINS_VOC','NAL_IMP_JOURNALS','ZKP_REF_D_CATEGORIES','CG_TPL_VOC_MEANINGS','IG_FOLDER_TYPE','DF_UNLOCK_AR','DF_STG_TASK','QUF_STAGES','UC_SYSTEM_VOC','BACKUP_CSE_CASES','ZKP_PROTOCOLS','ELA_AP_OPERATION','ADR_HISTORY','CSE_REL','UC_CATEGORY_ADD','ELA_SYSTEM_OPTIONS','IG_FOLDER_STATUS_TYPE','LOG$CRT_ADD','UC_STATUS_VOC','ELA_AP_STATUS' ,'ZKP_REF_CAT_PURP_NEW','EXP_VOC_MEANINGS','BAD_ROWS','DF_ROUTES','DF_UNLOCK_AR_DET','IG_REQUEST_TYPE','LOG$RT_CMP','ODS_104854000','ELA_REGISTERED_INSTALLATIONS','NAL_EXP_JOURNALS_TMP','ITO_NALOG_PARAM','GKN_LINKS','CG_TPL_VOC','NAL_CAD_FILE','TEMP_QU_RS_LIST_OBJ','TMP_RT_RIGHTS_REL','TMP_XXX_DUBL_GROUP','NAL_EXP_LOG_DEPTS','TEMP_QU_RS_LIST_OBJ','RE_UNOMS','NSI_TMP_CLOB','NSI_CATALOGS','NSI_CATALOGS_TEMP','NSI_CATALOGS_FIELDS','NSI_CATALOGS_FIELDS_TEMP','NOTICES_AUTO','CSE_REL','DF_UNLOCK_AR_DET' ,'RE_UNOMS_FIND','ODS_105029000','NSI_CATALOGS_ITEMS','NSI_CATALOGS_ITEMS_TEMP','NSI_CATALOGS_SUBSCRIBES','NSI_CATALOGS_NOTIFICATIONS','NSI_CATS_VOCS','NSI_CATS_VOCS_ITEMS','CPRT_ALL_INDEXES','CPRT_ALL_IND_COLUMNS','CPRT_ALL_IND_EXPRESSIONS','CPRT_ALL_CONSTRAINTS','CPRT_ALL_CONS_COLUMNS','ODS_104738000','QU_95362000','TMP_RT_RIGHTS_REL','TMP_XXX_DUBL_GROUP','NAL_EXP_LOG_DEPTS','TEMP_QU_RS_LIST_OBJ','TMP_RT_RIGHTS_REL','TMP_XXX_DUBL_GROUP','NAL_EXP_LOG_DEPTS','TEMP_QU_RS_LIST_OBJ','TMP_RT_RIGHTS_REL' ,'TMP_XXX_DUBL_GROUP','GKN_LINK_RE_QUERY','NAL_FIREEXPORT_LOG','TMP_RT_RIGHTS_REL','TMP_XXX_DUBL_GROUP','NAL_EXP_LOG_DEPTS','TEMP_QU_RS_LIST_OBJ','TMP_RT_RIGHTS_REL','TMP_XXX_DUBL_GROUP','NAL_EXP_LOG_DEPTS','TEMP_QU_RS_LIST_OBJ','TMP_RT_RIGHTS_REL','TMP_XXX_DUBL_GROUP','QU_92522000','QU_92525000','QU_92528000','TMP_ODS_SQ_2016','NAL_EXP_LOG_DEPTS','TEMP_QU_RS_LIST_OBJ','TMP_RT_RIGHTS_REL','TMP_XXX_DUBL_GROUP','NAL_EXP_LOG_DEPTS','TEMP_QU_RS_LIST_OBJ','TMP_RT_RIGHTS_REL','TMP_XXX_DUBL_GROUP','TMP_RT_RIGHTS_REL' ,'TMP_XXX_DUBL_GROUP','NAL_EXP_LOG_DEPTS','TEMP_QU_RS_LIST_OBJ','TMP_RT_RIGHTS_REL','TMP_XXX_DUBL_GROUP','NAL_EXP_LOG_DEPTS','TEMP_QU_RS_LIST_OBJ','TMP_RT_RIGHTS_REL','TMP_XXX_DUBL_GROUP','NAL_EXP_LOG_DEPTS','TEMP_QU_RS_LIST_OBJ','TMP_RT_RIGHTS_REL','TMP_XXX_DUBL_GROUP','NAL_EXP_LOG_DEPTS','TEMP_QU_RS_LIST_OBJ','TMP_RT_RIGHTS_REL','TMP_XXX_DUBL_GROUP','NAL_EXP_LOG_DEPTS','TEMP_QU_RS_LIST_OBJ','TMP_RT_RIGHTS_REL','TMP_XXX_DUBL_GROUP','NAL_EXP_LOG_DEPTS','TEMP_QU_RS_LIST_OBJ','TMP_RT_RIGHTS_REL','TMP_XXX_DUBL_GROUP' ,'NAL_EXP_LOG_DEPTS','TEMP_QU_RS_LIST_OBJ','TMP_RT_RIGHTS_REL','TMP_XXX_DUBL_GROUP','NAL_EXP_LOG_DEPTS','TEMP_QU_RS_LIST_OBJ','TMP_RT_RIGHTS_REL','TMP_XXX_DUBL_GROUP','NAL_EXP_LOG_DEPTS','TEMP_QU_RS_LIST_OBJ','TMP_RT_RIGHTS_REL','TMP_XXX_DUBL_GROUP','NAL_EXP_LOG_DEPTS','TEMP_QU_RS_LIST_OBJ','NAL_EXP_LOG_DEPTS','TEMP_QU_RS_LIST_OBJ','TMP_RT_RIGHTS_REL','TMP_XXX_DUBL_GROUP','NAL_EXP_LOG_DEPTS','TEMP_QU_RS_LIST_OBJ','TMP_RT_RIGHTS_REL','TMP_XXX_DUBL_GROUP','NAL_EXP_LOG_DEPTS','TEMP_QU_RS_LIST_OBJ','NAL_EXP_LOG_DEPTS' ,'TEMP_QU_RS_LIST_OBJ','TMP_RT_RIGHTS_REL','TMP_XXX_DUBL_GROUP','NAL_EXP_LOG_DEPTS','DYN_VALUES','DS_ACTION_JOURNAL','DS_MODULE_JOURNAL','DS_MODULES','DS_PACKAGE_JOURNAL','DS_PACKAGES_ACL','DYN_FACTORS','CSE_SHELFS','CSE_SHELFS_EMPS','BDF_BOXES','BDF_BOX_REL','BDF_CSE_ORDER','ADR_ENT','ELA_EXPORT_HISTORY','ELA_FILE_LOCATION','EXP_FIR_IMPORTS','LOG$ADR_HISTORY','LOG_BACKUP_JOURNAL','LOG$BDF_BOXES','LOG$BDF_BOX_REL','LOG$CSE_FRM','LOG$CSE_REL','LOG$CSE_SHELFS','LOG$CSE_SHELFS_EMPS','LOG$DF_UNLOCK_AR' ,'LOG$DF_UNLOCK_AR_DET','LOG$DOC_NOTAR_VOC','LOG$DYN_VALUES','LOG$QUF_FLD_QU_APP','LOG$QUF_FOLDERS','LOG$QUF_PROCESSINGS','LOG$RP_LOCAL_DEPTS','LOG$VOL_QUE_EMPS','QUF_DEF_EMP_STG','QUF_FLD_QU_APP','QUF_FOLDERS','QUF_PROCESSINGS','RP_GROUP_CONTENTS','RP_LOCAL_GROUP','VOL_QUE_EMPS','MIZO','NOTICES_AUTO','IG_EVENTS','BACKUP_CSE_HISTORY','JNL_LOG','LOG_DETAILS','LOG_LOG','P_CONSUMER_QU_ROLE','EXCEL','ZKP_ADR_TOPONIMS','ZKP_SUB_OBJECTS','DS_ENTITIES_JOURNAL','DS_PACKAGES','DS_SESSION_JOURNAL','EXP_JOB_MEANINGS' ,'JNL_LOG_DET','P_REQUESTS','QU_REF_DOCS','QU_REF_DOCS_BUF','RP_COMPUTERS','RP_DATABASES','RP_REPLICA','RP_REPLICA_JOURNAL','ODS_104996000')

/

SELECT task_id task_id, step step FROM public.task