#!/bin/bash

. $(dirname $0)/.config

: ${FROM_DB_USER?"You must define FROM_DB_USER to continue"}
: ${FROM_DB_NAME?"You must define FROM_DB_NAME to continue"}
: ${DB_BIN_TO_DUMP_COEFF?"You must define DB_BIN_TO_DUMP_COEFF to continue"}
: ${DB_OBJECTS_SIZE_FILTER?"You must define DB_OBJECTS_SIZE_FILTER to continue"}

# Cat, not read because non-0 exit code will not satisfy us http://stackoverflow.com/questions/1167746/how-to-assign-a-heredoc-value-to-a-variable-in-bash
SQL=$(cat <<HEREDOC
	SELECT row_to_json(t)
	FROM (
		SELECT
			CEIL(SUM(pg_total_relation_size((table_catalog || '.' || table_schema || '.' || table_name)::regclass::oid))) AS sum_size
			,pg_size_pretty(CEIL(SUM(pg_total_relation_size((table_catalog || '.' || table_schema || '.' || table_name)::regclass::oid)))) AS sum_size_pretty
		FROM information_schema.tables
		WHERE table_schema NOT IN ('pg_catalog', 'information_schema', 'hint_plan') $DB_OBJECTS_SIZE_FILTER
			AND table_type != 'FOREIGN'
	) t
HEREDOC
)

. $(dirname $0)/_shared

SIZE=$( run FROM psql -h $FROM_DB_HOST -p $FROM_DB_PORT -U $FROM_DB_USER -qtAw --dbname $FROM_DB_NAME -c "$SQL" )
echo EXPECTED_SIZE=$SIZE
SIZE=$( echo "$SIZE" | jq .sum_size )
echo 'NOTICE: Please note - used size from database and it is very roughly estimated!'
