#!/bin/bash

. $(dirname $0)/.config

. $(dirname $0)/_pg_size

time pg_dump -U postgres --clean --if-exists --compress=0 --format=p --encoding=UTF-8 --exclude-table-data='history.logged_actions' egais \
	| pv --progress -terabW --size $SIZE \
	| pigz -9 \
	> egais_dump-$(date +'%F-%H_%M_%S').sql.gz
