#!/bin/bash

: ${1?"Please provide file to restore from. Like: $(basename $0) egais_dump-2017-06-28-13_02_28.sql.gz"}

time pigz --decompress --stdout "$1" \
	| pv --progress -terabW --size $( pigz --decompress --stdout "$1" | wc -c ) \
	| psql -h localhost -p 5432 -U postgres egais

# Pg_restore if is not PLAIN format used:
#	| pg_restore -h localhost -p 5432 -U postgres --clean --create --exit-on-error --no-data-for-failed-tables
